"""empty message

Revision ID: 600800f77868
Revises: eeb96b9613a9
Create Date: 2020-09-07 00:23:58.006915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '600800f77868'
down_revision = 'eeb96b9613a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('user_properties',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('property_id', 'user_id')
    )
    op.create_table('survey_properties',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ),
    sa.PrimaryKeyConstraint('property_id', 'survey_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey_properties')
    op.drop_table('user_properties')
    op.drop_table('property')
    # ### end Alembic commands ###
