"""empty message

Revision ID: 74de44c2b8e3
Revises: 600800f77868
Create Date: 2020-09-07 02:18:13.242191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74de44c2b8e3'
down_revision = '600800f77868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('properties', sa.String(length=500), nullable=True))
    op.add_column('user', sa.Column('properties', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'properties')
    op.drop_column('survey', 'properties')
    # ### end Alembic commands ###
